# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- neos-release

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir'
- task: CMake@1
  inputs:
    workingDirectory: 
    cmakeArgs: 'CMakeLists.txt -G "Visual Studio 16 2019"'
- task: VSBuild@1
  inputs:
    solution: 'Assimp.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'bin/Release'
    Contents: 'assimp-vc142-mt.dll'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'windows_x64'
    publishLocation: 'Container'