# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- neos-release

pool:
  vmImage: windows-latest

steps:
- task: CMake@1
  inputs:
    cmakeArgs: '-G "Visual Studio 16 2019"'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir'