trigger:
- neos-release

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      cmakeTarget: 'Unix Makefiles'
    windows:
      imageName: 'windows-latest'
      cmakeTarget: 'Visual Studio 16 2019'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    workingDirectory: 
    cmakeArgs: 'CMakeLists.txt -G "$(cmakeTarget)"'

- task: VSBuild@1
  inputs:
    solution: 'Assimp.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  
- task: Bash@3
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      make
      ls
  condition: eq( variables['Agent.OS'], 'Linux' )

- task: CopyFiles@2
  inputs:
    SourceFolder: 'bin/Release'
    Contents: 'assimp-vc142-mt.dll'
    TargetFolder: '$(build.artifactstagingdirectory)/Assimp64.dll'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'windows_x64'
    publishLocation: 'Container'